// Original Hindi/Nepali teaching. References guide the content; no modern
// copyrighted translation or full user PDF is reproduced or published.
const p=(t,v,extra={})=>({t,v,...extra});
const poses=[
 {id:'mountain',name:'ताड़ासन · Tadasana',tag:'Standing awareness',steps:['दोनों पैरों को आराम से hip-width पर रखें; एड़ियों और पैर के आगे के हिस्से पर भार बाँटें।','घुटनों को जोर से lock न करें। श्रोणि के ऊपर पसलियाँ और उनके ऊपर सिर रखें; कंधे नरम।','हाथ बगल में, दृष्टि सामने। 4–6 सहज श्वास तक खड़े रहें, फिर पैर हिलाएँ।'],breath:'श्वास स्वाभाविक रखें; पेट खींचकर श्वास रोकना नहीं।',modify:'संतुलन कठिन हो तो दीवार पास रखें; chair पर सीधे बैठकर यही awareness कर सकते हैं।',mistake:'छाती को बहुत आगे निकालना या घुटने पीछे धकेलना।',exit:'भार दोनों पैरों पर समान करें और आराम से कदम लें।'},
 {id:'cat',name:'मार्जारी–बितिल · Cat–Cow',tag:'Spine mobilisation',steps:['हथेलियाँ कंधों के नीचे और घुटने hips के नीचे; घुटनों के लिए blanket रखें।','सहज inhale पर छाती थोड़ा आगे, spine हल्की लंबी; गर्दन पीछे न फेंकें।','Exhale पर पीठ धीरे गोल करें और सिर सहज झुकाएँ। 4–6 छोटे, दर्दरहित चक्र; अंत में neutral spine।'],breath:'हर movement एक सहज श्वास के साथ; बहुत गहरा range आवश्यक नहीं।',modify:'Wrist/knee discomfort हो तो chair पर बैठकर हाथ जाँघों पर रखकर छोटी spine movement करें।',mistake:'कमर में जोर से arch बनाना या हथेलियों में पूरा भार पटकना।',exit:'Neutral spine में आएँ; धीरे बैठें या खड़े हों।'},
 {id:'warrior',name:'वीरभद्रासन II · Warrior II',tag:'Standing strength',steps:['पैर चौड़े लेकिन नियंत्रित दूरी पर; दायाँ पैर बाहर की ओर, बायाँ थोड़ा अंदर।','दायाँ घुटना मोड़ें और उसे पैर की दिशा में रखें; आरामदायक bend, आगे का घुटना अंदर न गिरे।','हाथ shoulder height पर यदि आरामदेह हों; pelvis और chest side की ओर। 3–4 श्वास, फिर पैर सीधा करें और दूसरी ओर।'],breath:'श्वास रोके बिना स्थिर रहें; बोलने/सहज सांस में कठिनाई हो तो bend कम करें।',modify:'Stance छोटा करें, घुटना कम मोड़ें; एक हाथ chair पर या दोनों हाथ hips पर।',mistake:'गहरा bend पाने के लिए घुटने को अंदर गिराना या कंधे कानों तक उठाना।',exit:'पहले आगे का पैर सीधा करें, फिर पैरों को parallel करके stance छोटा करें।'},
 {id:'triangle',name:'त्रिकोणासन · Supported Triangle',tag:'Length before depth',steps:['मध्यम चौड़ा stance लें; सामने का पैर बाहर, पीछे का पैर थोड़ा अंदर, दोनों घुटने नरम।','धड़ लंबा रखते हुए आगे के hip से छोटा hinge करें; नीचे वाला हाथ chair/स्थिर block पर।','ऊपरी हाथ hip पर रह सकता है। Chest थोड़ा side की ओर, नजर जमीन पर। 3 सहज श्वास और दूसरी ओर।'],breath:'श्वास के लिए जगह रखें; पेट/पसलियों को दबाकर नीचे न जाएँ।',modify:'ऊँचा support और छोटा stance; चक्कर हो तो standing mountain में रहें।',mistake:'हाथ जमीन तक पहुँचाने के लिए spine को collapse करना।',exit:'घुटने हल्के मोड़ें, पैरों का सहारा लेते हुए धड़ उठाएँ; जल्दी सिर न उठाएँ।'},
 {id:'tree',name:'वृक्षासन · Supported Tree',tag:'Balance with support',steps:['दीवार/chair के पास खड़े हों; एक पैर पर धीरे भार लें, दूसरा पैर toes जमीन पर रखकर ankle के पास रखें।','यदि स्थिर हों तो पैर calf पर रख सकते हैं; घुटने के जोड़ पर दबाव न दें।','Pelvis सामने और नजर एक स्थिर बिंदु पर। 2–4 श्वास, पैर नीचे और दूसरी ओर।'],breath:'सहज श्वास; संतुलन खोना अभ्यास का हिस्सा है।',modify:'दोनों हाथ chair पर और दूसरे पैर की toes हमेशा जमीन पर रखें।',mistake:'पैर को सीधे knee joint पर दबाना या आंखें बंद करके चुनौती बढ़ाना।',exit:'पैर को जमीन पर रखें, दोनों पैरों पर भार बाँटें, तभी side बदलें।'},
 {id:'fold',name:'अर्ध उत्तानासन · Supported Half Fold',tag:'Hip hinge',steps:['Chair/दीवार के सामने खड़े हों; हाथ support पर और कदम पीछे करके आरामदायक hinge बनाएं।','घुटने थोड़ा मोड़ें; hips पीछे, spine लंबी, सिर spine की line में।','3–5 सहज श्वास; ऊंचाई ऐसी रखें कि पीठ या hamstrings में खिंचाव दर्द न बने।'],breath:'गर्दन और पेट नरम; श्वास रोककर खिंचाव नहीं।',modify:'हाथ ऊँची दीवार पर रखें और बहुत छोटा hinge; नीचे सिर करने से परेशानी हो तो upright रहें।',mistake:'घुटने lock करके कमर को गोल धकेलना।',exit:'घुटने नरम करके धीरे ऊपर आएँ; पहले चक्कर तो नहीं, यह देखें।'},
 {id:'cobra',name:'भुजंगासन · Low Cobra',tag:'Small backbend',steps:['पेट के बल लेटें, पैर आराम से पीछे; हथेलियाँ निचली पसलियों के पास, elbows पास।','Inhale पर छाती थोड़ा ऊपर लाएँ; हाथों से जोर लगाकर ऊँचा नहीं। Pelvis और पैर जमीन पर सहज।','गर्दन लंबी, नजर आगे-नीचे। 1–2 श्वास या एक सहज inhale/exhale; 2–3 छोटे repetitions।'],breath:'ऊपर हल्का inhale, नीचे सहज exhale; श्वास/कमर दबे तो तुरंत नीचे।',modify:'पेट के बल होना असुविधाजनक हो तो यह छोड़कर chair पर gentle chest opening करें।',mistake:'Straight arms के लिए कमर को दबाना और सिर बहुत पीछे करना।',exit:'Exhale पर छाती नीचे, सिर एक ओर या हाथों पर आराम।'},
 {id:'bridge',name:'सेतुबंधासन · Gentle Bridge',tag:'Controlled hip lift',steps:['पीठ के बल लेटें; घुटने मुड़े, पैर hip-width और heels आराम से hips के पास।','Inhale पर hips थोड़े उठाएँ; घुटने पैर की दिशा में। भार shoulders/पैरों पर, गर्दन पर दबाव नहीं।','2–3 सहज श्वास या छोटे up/down repetitions। सिर को उठे हुए pose में side की ओर न मोड़ें।'],breath:'श्वास सहज; ऊंचाई से ज्यादा control महत्वपूर्ण।',modify:'बहुत छोटी lift या hips जमीन पर रखते हुए पैर का gentle press।',mistake:'सबसे ऊंची lift के लिए lower back दबाना या pose में गर्दन घुमाना।',exit:'धीरे hips जमीन पर रखें, फिर आराम करें।'},
 {id:'rest',name:'शवासन · Supported Rest',tag:'Recovery',steps:['पीठ के बल सहज लेटें; घुटनों के नीचे pillow, सिर के नीचे पतला support जरूरत के अनुसार।','हाथ आराम से बगल में; आंखें बंद करना जरूरी नहीं। शरीर का भार support पर छोड़ें।','2–4 मिनट कोई श्वास बदलने का लक्ष्य नहीं; पैर, pelvis, shoulders, चेहरे की सहजता देखें।'],breath:'श्वास को अपने आप आने-जाने दें।',modify:'Side-lying with pillow या chair पर supported rest; शरीर या breath पर ध्यान असहज हो तो कमरे की आवाज़ सुनें।',mistake:'आराम को भी perfect करने की कोशिश; uncomfortable posture में टिके रहना।',exit:'उंगलियाँ हिलाएँ, side पर मुड़ें, हाथ का सहारा लेकर धीरे उठें।'},
 {id:'seat',name:'सुखासन / Chair Seat · Meditation Seat',tag:'Stable and comfortable',steps:['Chair पर बैठें तो पैर जमीन पर, hips स्थिर और पीठ आराम से लंबी। Floor पर cushion ऊँचा रखें; knees को support दे सकते हैं।','कंधे, jaw और हाथ नरम; आंखें हल्की खुली या बंद—अपनी सहजता के अनुसार।','हर 1–2 मिनट posture देखें। Pain या numbness हो तो position बदलें; ध्यान के लिए lotus आवश्यक नहीं।'],breath:'स्वाभाविक श्वास; posture इतना कठोर न करें कि सांस दबे।',modify:'Chair या supported back वाला आसन पूरी तरह मान्य है।',mistake:'Padmasana में पैरों को जबरदस्ती खींचना या सुन्न होने पर भी न हिलना।',exit:'आंखें खोलें, आसपास देखें, पैरों को धीरे सीधा करें और फिर खड़े हों।'}
];
const meditations=[
 {id:'breath',name:'श्वास-दृष्टि · Breath Awareness',minutes:'4–8',steps:['1 मिनट posture और कमरे का संपर्क महसूस करें। Chair का सहारा भी ठीक है।','एक anchor चुनें: नासिका पर सहज श्वास, पेट की हल्की movement, या कमरे की आवाज़।','2–5 मिनट anchor महसूस करें। मन भटके तो मन में “विचार” कहें और नरमी से वापस आएँ; सांस को लंबा बनाने की जरूरत नहीं।','अंतिम 1 मिनट पूरे शरीर/कमरे को देखें और आंखें खोलें।'],key:'ध्यान का कौशल विचार खत्म करना नहीं—भटकना पहचानकर लौटना है।',adapt:'Breath focus से घबराहट हो तो आंखें खोलें, पैर जमीन पर महसूस करें और बाहरी आवाज़ को anchor बनाएं।'},
 {id:'alternate',name:'अनुलोम–विलोम · बिना कुम्भक',minutes:'2–3',steps:['आराम से बैठें। बाएँ हाथ को आराम दें; दाहिने हाथ से नासिका को बहुत हल्के स्पर्श से बंद करें।','दाहिनी नासिका बंद: बाईं से सहज inhale। बाईं बंद करके दाहिनी खोलें: सहज exhale।','दाहिनी से सहज inhale; दाहिनी बंद करके बाईं खोलें: सहज exhale। यह एक चक्र है।','4–6 आरामदेह चक्र तक या 2 मिनट के भीतर रखें। कोई breath hold, जोरदार inhale या निश्चित ratio नहीं। अंत में दोनों नासिकाओं से सामान्य श्वास।'],key:'श्वास सहज रहे; नासिका बंद हो तो plain breath awareness करें।',adapt:'हाथ थके, सांस कम लगे या चक्कर आए तो हाथ नीचे और सामान्य श्वास। यह बीमारी का उपचार या “detox” नहीं है।'},
 {id:'mantra',name:'जप-ध्यान · Optional Mantra',minutes:'5–8',steps:['एक परिचित और अर्थपूर्ण शब्द चुनें—जैसे “ॐ” या “शान्ति”; धार्मिक जप चुनना जरूरी नहीं।','30–60 seconds सहज बैठें। हर कुछ श्वास पर चुना हुआ शब्द मन में धीरे दोहराएँ; breath को शब्द के हिसाब से जोर न दें।','मन भटके तो शब्द/आवाज पर वापस। तेज chanting, लंबा breath hold या throat pressure नहीं।','अंत में शब्द छोड़कर एक मिनट चुप बैठें और कमरे से दोबारा जुड़ें।'],key:'जप एक attention anchor है; दिव्य अनुभूति को परीक्षा या guaranteed result न बनाएं।',adapt:'यदि जप पसंद नहीं तो breath awareness या बाहरी आवाज़ चुनें।'},
 {id:'witness',name:'साक्षीभाव · Observe Without Fighting',minutes:'5–8',steps:['पहले 2 मिनट breath या sound anchor पर रहें।','फिर कोई विचार आए तो छोटा label: “योजना”, “याद”, “चिंता”। कहानी में आगे जाने के बजाय anchor महसूस करें।','Thoughts को दबाएँ नहीं। बार-बार भटकने पर attention को अधिक सरल बाहरी sound/पैर के संपर्क पर लौटाएँ।','अंतिम मिनट आंखें खोलें और तीन चीजें देखें; meditation समाप्त होने को पहचानें।'],key:'यह एक contemplative अभ्यास है; कठिन भावना को सहते रहने की मजबूरी नहीं।',adapt:'Panic, unreality या overwhelm हो तो रोकें, आंखें खोलकर जमीन/कमरे से जुड़ें। बार-बार परेशानी हो तो योग्य सहायता लें।'},
 {id:'walk',name:'सचेत चलना · Walking Attention',minutes:'4–6',steps:['समतल सुरक्षित जगह चुनें; आंखें खुली और रास्ते पर ध्यान।','सामान्य धीमी गति से चलें; पैर का उठना, आगे बढ़ना और जमीन छूना महसूस करें।','सोच में खो जाएँ तो अगले एक कदम पर वापस; सांस और कदम का forced ratio नहीं।','अंत में रुककर दो सहज श्वास लें। यह running challenge नहीं।'],key:'ध्यान बैठने तक सीमित नहीं; movement में भी लौटने का अभ्यास हो सकता है।',adapt:'Chair पर बैठे हुए पैर का संपर्क/आवाज़ महसूस करना भी विकल्प है।'}
];
const gita=[
 {id:'seat',ref:'गीता 6.12–14',pages:'434–436',title:'स्थिरता और एकाग्रता',meaning:'ध्यान में जगह, बैठने की स्थिरता और एक दिशा में मन लगाने का महत्व है। इस course में उसका व्यावहारिक रूप: comfortable seat, नरम posture और एक attention anchor। यह हमारी अभ्यास-व्याख्या है; श्लोक chair या आधुनिक stretching routine का निर्देश नहीं देते।',reflection:'आज कौन-सा बैठने का support तुम्हारी श्वास को सहज रखता है?'},
 {id:'moderation',ref:'गीता 6.16–17',pages:'438–439',title:'युक्त आहार-विहार · संतुलित अभ्यास',meaning:'अति और उपेक्षा दोनों से बचकर आहार, activity, काम और आराम में संयम रखने का संदेश। इसका अभ्यास में अर्थ: थके दिन intensity घटाना और पर्याप्त recovery रखना। यह कोई विशेष diet, fasting या नींद छोड़ने की prescription नहीं है।',reflection:'आज अधिक करना चाहने के बजाय किस सीमा का सम्मान कर सकते हो?'},
 {id:'return',ref:'गीता 6.26',pages:'456',title:'मन भटके तो फिर लौटना',meaning:'मन अलग-अलग ओर जाए तो बार-बार उसे साधना के लक्ष्य की ओर लौटाना। हम पहले breath/sound anchor पर कोमल return सीखते हैं; गीता के आध्यात्मिक संदर्भ में लक्ष्य आत्मा/परमात्मा का ध्यान है। दोनों संदर्भों को एक जैसा दावा नहीं करते।',reflection:'ध्यान भटका तब तुम्हारा स्वर कठोर था या धैर्यपूर्ण?'},
 {id:'practice',ref:'गीता 6.35',pages:'467–468',title:'अभ्यास और वैराग्य',meaning:'चंचल मन के साथ नियमित अभ्यास और आसक्ति से दूरी—दोनों की भूमिका। आज का व्यावहारिक संकल्प: छोटे नियमित sessions और अनुभव/अंक/गहरे pose के प्रति अनावश्यक चिपकाव कम करना। इसे instant control या guaranteed spiritual achievement न समझें।',reflection:'कौन-सा परिणाम छोड़कर केवल अभ्यास की गुणवत्ता पर ध्यान दे सकते हो?'}
];
const rows=[
 ['steady','स्थिरता, श्वास और अभ्यास की गुणवत्ता','तुम्हारे परिचित सूर्यनमस्कार को धीमे निरीक्षण के साथ करना।',['mountain','cat','seat'],'breath','seat','सूर्यनमस्कार में एक transition चुनो। Inhale/exhale सहज है या गति के पीछे श्वास दबती है? अगला round धीमा करो; कम rounds भी ठीक हैं।','Sun salutation की तुम्हारी परिचित variation ही करो। Full 12-position sequence नया सीखना हो तो in-person alignment guidance लो; इस session में नई कठिन variation जोड़ना लक्ष्य नहीं।'],
 ['balance','संतुलन और पैरों का आधार','Balance में support लेना और steady breath बनाए रखना।',['mountain','warrior','tree'],'breath','return','दीवार के पास Tree को पहले toes जमीन पर रखकर करो। एक side अधिक कठिन हो तो समय बराबर रखने के लिए strain न बढ़ाओ।','Focused movement में Warrior II दोनों ओर 3 श्वास और Supported Tree दोनों ओर 2–3 श्वास, बीच में Mountain rest। समय भरने के लिए repetitions जरूरी नहीं।'],
 ['mobility','Spine movement और नियंत्रित strength','छोटे range में movement करना और recovery को अभ्यास मानना।',['cat','cobra','bridge','rest'],'breath','moderation','आज low cobra/bridge की ऊँचाई कम रखो। कमर में compression हो तो alternative चुनो; उसे progress का प्रमाण न मानो।','Cat–Cow 4 सहज cycles; Low Cobra 2 छोटे repetitions; Gentle Bridge 2 छोटे repetitions। हर movement के बीच neutral/rest। परिचित pose न हो तो पहले guide पढ़ो और chair विकल्प चुनो।'],
 ['restore','Recovery और साक्षीभाव','हल्का दिन रखना, विचारों से लड़ने के बजाय लौटना।',['fold','rest','seat'],'witness','moderation','Running को yoga session के ऊपर extra intensity की तरह न जोड़ो। आज चाहो तो running की जगह आरामदेह walking चुनो।','हल्का Supported Half Fold 2–3 सहज श्वास, फिर Supported Rest। आज सूर्यनमस्कार कम intensity में या छोड़कर seated/chair warm-up कर सकते हो।'],
 ['flow','Controlled standing flow','आसन के बीच safe transition और breath की continuity।',['mountain','warrior','triangle','tree'],'breath','practice','Mountain → Warrior II → Mountain → Supported Triangle → Mountain। हर side अलग करो। Speed नहीं, controlled entry और exit देखो।','Focused movement: Warrior II दोनों ओर 3 श्वास, supported Triangle दोनों ओर 3 श्वास। Balance ठीक हो तो supported Tree 2 श्वास; नहीं तो Mountain।'],
 ['breathing','सहज प्राणायाम और वैकल्पिक जप','Breath retention के बिना attention और श्वास की सहजता।',['cat','seat','rest'],'mantra','return','आज breath segment में अनुलोम–विलोम के 4 सहज cycles का विकल्प है; blocked nose या discomfort हो तो सामान्य श्वास। Meditation में optional शान्ति जप।','Light Cat–Cow/chair mobilisation और comfortable seat चुनो। Pranayama में fixed counts, कुम्भक, bandha, forceful kapalabhati/bhastrika नहीं। Familiar Sun Salutation को आसान intensity पर रखो।'],
 ['integrate','Review और अपनी routine बनाना','सात sessions की समझ से टिकाऊ, adaptable अभ्यास चुनना।',['mountain','warrior','rest','seat'],'walk','practice','आज अपने लिए एक standing pose चुनो, उसकी entry/exit बिना देखे समझाओ। ध्यान भटके तो return करो। Next session चुनते समय fatigue और श्वास देखो।','Review day: परिचित सूर्यनमस्कार या comfortable mobility; केवल एक familiar focused pose, फिर walking attention का विकल्प। कोई maximum flexibility या longest-hold परीक्षा नहीं।']
];
const sessions=rows.map((r,i)=>({id:'yoga:intermediate:1.'+(i+1),day:i+1,title:r[1],goal:r[2],poses:r[3],meditation:r[4],gita:r[5],task:r[6],focus:r[7],quiz:{id:'yoga:quiz:1.'+(i+1),quiz:[
 {q:'आसन में तेज दर्द या चक्कर आए तो क्या करें?',options:['थोड़ा और जोर लगाएँ','अभ्यास रोकें, safe position और सहज श्वास लें','दर्द को mastery समझें'],correct:1,why:'Pain/dizziness चुनौती बढ़ाने का संकेत नहीं। नया/लगातार लक्षण हो तो उपयुक्त चिकित्सा सहायता लें।'},
 {q:'मन बार-बार भटके तो ध्यान असफल है?',options:['नहीं; ध्यान पहचानकर कोमलता से लौटाना अभ्यास है','हाँ; विचार बिल्कुल नहीं आने चाहिए','श्वास रोकने से ही ध्यान होगा'],correct:0,why:'ध्यान लौटने का कौशल है; breath hold या thoughts suppression आवश्यक नहीं।'},
 {q:i===5?'इस course में अनुलोम–विलोम कैसे है?':'आज progress का उपयोगी संकेत कौन-सा है?',options:i===5?['जोरदार inhale और लंबा hold','सहज breathing, कोई retention नहीं','नासिका बंद हो तब भी जबरदस्ती']:['सबसे कठिन pose','दूसरे से अधिक rounds','सहज श्वास, नियंत्रित movement और अपनी सीमा पहचानना'],correct:i===5?1:2,why:i===5?'यह variant comfortable alternate breathing तक सीमित है।':'Intensity या duration अकेला progress नहीं; quality और recovery देखें।'}
 ]}}));
module.exports={poses,meditations,gita,sessions};
